env:
  browser: true
  es2021: true
extends:
  - plugin:vue/vue3-essential
  - airbnb-base
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - vue
rules: {
  semi: ['error', 'always'],
  quotes: ['error', 'single'],
}
